spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234